"""Create database

Revision ID: fd675312897e
Revises: 
Create Date: 2024-04-21 11:17:55.488014

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd675312897e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ac_devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("identifier", sa.BigInteger(), nullable=True),
        sa.Column("key", sa.String(), nullable=True),
        sa.Column("token", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ip_address"),
    )
    with op.batch_alter_table("ac_devices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ac_devices_name"), ["name"], unique=True)

    op.create_table(
        "broadlink_actions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("packet", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("broadlink_actions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_broadlink_actions_name"), ["name"], unique=True
        )

    op.create_table(
        "broadlink_devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ip_address"),
    )
    with op.batch_alter_table("broadlink_devices", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_broadlink_devices_name"), ["name"], unique=True
        )

    op.create_table(
        "hue_bridges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("identifier", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("client_key", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ip_address"),
    )
    with op.batch_alter_table("hue_bridges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_hue_bridges_name"), ["name"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hue_bridges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hue_bridges_name"))

    op.drop_table("hue_bridges")
    with op.batch_alter_table("broadlink_devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_broadlink_devices_name"))

    op.drop_table("broadlink_devices")
    with op.batch_alter_table("broadlink_actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_broadlink_actions_name"))

    op.drop_table("broadlink_actions")
    with op.batch_alter_table("ac_devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ac_devices_name"))

    op.drop_table("ac_devices")
    # ### end Alembic commands ###
